### ISSUE TITLE
UnicodeEncodeError: 'decimal' codec can't encode characters in position 0-65: invalid decimal Unicode string

### ISSUE THREAD

**Issue by olaszfiu** [wting/autojump#264]
Hi,
I get a UnicodeEncodeError error after a fresh installation of autojump:

[root@clueet rosario]# git clone git://github.com/joelthelion/autojump.git
Cloning into 'autojump'...
remote: Reusing existing pack: 2578, done.
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 2586 (delta 3), reused 0 (delta 0)
Receiving objects: 100% (2586/2586), 698.15 KiB | 458.00 KiB/s, done.
Resolving deltas: 100% (1470/1470), done.

[root@clueet rosario]# cd autojump/
[root@clueet autojump]# ./install.py
Installing autojump to /root/.autojump ...
creating directory: /root/.autojump/bin
creating directory: /root/.autojump/share/man/man1
creating directory: /root/.autojump/share/autojump
copying file: ./bin/autojump -> /root/.autojump/bin
copying file: ./bin/autojump_argparse.py -> /root/.autojump/bin
copying file: ./bin/autojump_data.py -> /root/.autojump/bin
copying file: ./bin/autojump_utils.py -> /root/.autojump/bin
copying file: ./bin/icon.png -> /root/.autojump/share/autojump
copying file: ./docs/autojump.1 -> /root/.autojump/share/man/man1
creating directory: /root/.autojump/etc/profile.d
creating directory: /root/.autojump/functions
copying file: ./bin/autojump.sh -> /root/.autojump/etc/profile.d
copying file: ./bin/autojump.bash -> /root/.autojump/etc/profile.d
copying file: ./bin/autojump.fish -> /root/.autojump/etc/profile.d
copying file: ./bin/autojump.zsh -> /root/.autojump/etc/profile.d
copying file: ./bin/_j -> /root/.autojump/functions

Please manually add the following line(s) to ~/.bashrc:

```
[[ -s /root/.autojump/etc/profile.d/autojump.sh ]] && source /root/.autojump/etc/profile.d/autojump.sh
```

Please restart terminal(s) before running autojump.

[root@clueet autojump]# [[ -s /root/.autojump/etc/profile.d/autojump.sh ]] && source /root/.autojump/etc/profile.d/autojump.sh
[root@clueet autojump]# j --stat
Traceback (most recent call last):
  File "/root/.autojump/bin/autojump", line 411, in <module>
    sys.exit(main(parse_arguments()))
  File "/root/.autojump/bin/autojump", line 387, in main
    print_stats(load(config), config['data_path'])
  File "/root/.autojump/bin/autojump_data.py", line 78, in load
    ifilter(correct_length, imap(parse, f))))
  File "/root/.autojump/bin/autojump_data.py", line 68, in <lambda>
    tupleize = lambda x: (x[1], float(x[0]))
UnicodeEncodeError: 'decimal' codec can't encode characters in position 0-65: invalid decimal Unicode string

**Comment by bariscicek** [comment]
[autojump.txt](https://github.com/wting/autojump/files/859263/autojump.txt)

Not sure how that ^@ characters landed there, but I had a same problem, so reopenning it.

**Comment by VijayAshokGaikwad** [comment]
Hi I am getting an error while running this: 

sudo python vector_test.py  


Traceback (most recent call last):
  File "vector_test.py", line 12, in <module>
    en_model = KeyedVectors.load_word2vec_format('Newvectors.txt')
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/keyedvectors.py", line 1438, in load_word2vec_format
    limit=limit, datatype=datatype)
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/utils_any2vec.py", line 173, in _load_word2vec_format
    vocab_size, vector_size = (int(x) for x in header.split())  # throws for invalid file format
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/utils_any2vec.py", line 173, in <genexpr>
    vocab_size, vector_size = (int(x) for x in header.split())  # throws for invalid file format
UnicodeEncodeError: 'decimal' codec can't encode characters in position 0-2: invalid decimal Unicode string

The "Newvectors.txt" file contains wordembeddings in Devnagari Script. At position 0-2, there is string written in Devnagari.  

I have tried it using : 
en_model = KeyedVectors.load_word2vec_format('Newvectors.txt', binary=False, encoding='utf-8', unicode_errors='ignore'). But this didn't solve the problem. Still same error is shown.

Please Help.
