### ISSUE TITLE
autojump dies when there is wildcard(*) in path

### ISSUE THREAD

**Issue by lowks** [wting/autojump#402]
When I try to do this:

```autojump *top```

This happens:

```
Traceback (most recent call last):
  File "/usr/bin/autojump", line 420, in <module>
    sys.exit(main(parse_arguments()))
  File "/usr/bin/autojump", line 414, in main
    ['.'])))
  File "/usr/share/autojump/autojump_utils.py", line 42, in first
    return it.__next__()
  File "/usr/bin/autojump", line 287, in <lambda>
    flags=regex_flags)
  File "/usr/lib/python3.4/re.py", line 170, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.4/re.py", line 294, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.4/sre_compile.py", line 568, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.4/sre_parse.py", line 780, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python3.4/sre_parse.py", line 377, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python3.4/sre_parse.py", line 586, in _parse
    raise error("nothing to repeat")
sre_constants.error: nothing to repeat
```

**Comment by wting** [comment]
What shell are you using? In Bash and zsh, `*` gets expanded before it's passed to `cd`. For example in zsh:

```zsh
╭─ting@noa ~ ‹python-2.7.3›
╰─➤  mkdir "*top"
╭─ting@noa ~ ‹python-2.7.3›
╰─➤  cd *top
cd:cd:10: string not in pwd: Desktop
╭─ting@noa ~ ‹python-2.7.3›
╰─➤  ls
bin/  code/  Desktop/  downloads/  *top/
╭─ting@noa ~ ‹python-2.7.3›
╰─➤  cd \*top
╭─ting@noa ~/*top ‹python-2.7.3›
╰─➤  ..
╭─ting@noa ~ ‹python-2.7.3›
╰─➤  rm -fr \*top
╭─ting@noa ~ ‹python-2.7.3›
╰─➤
```

**Comment by lowks** [comment]
```
~/deployment » zsh --version
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
```

**Comment by wting** [comment]
k, I'm using zsh v4.3.17. This might be related to [glob expansion](http://zsh.sourceforge.net/Doc/Release/Expansion.html).

What's the result of `setopt | grep glob`?

**Comment by lowks** [comment]
```
 lowks  ~  setopt | grep glob                                                                                                                                                        .git 
nocaseglob
extendedglob
kshglob
```

**Comment by wting** [comment]
Even mimicking your settings I can't reproduce. I'll need to retry this with zsh v5 when I have more time:

```zsh
╭─ting@noa ~ ‹python-2.7.3›
╰─➤  setopt | grep glob
nocaseglob
extendedglob
kshglob
╭─ting@noa ~ ‹python-2.7.3›
╰─➤  cd *e
cd:cd:10: string not in pwd: code
╭─ting@noa ~ ‹python-2.7.3›
╰─➤
```

**Comment by lowks** [comment]
Could it be a terminal thing ? I tried on gnome-terminal it works but on
terminator it has this problem

**Comment by marekjm** [comment]
It is a regex thing. If the `*` is passed to autojump it tries to compile it as a special character, and fails - which is what the `sre_constants.error: nothing to repeat` is about. This [pull request](https://github.com/wting/autojump/pull/412) should fix the problem.

**Comment by wting** [comment]
FYI the [fix](https://github.com/wting/autojump/blob/master/bin/autojump_match.py#L81) was pushed recently. If this is still a problem on non-Windows machines, please re-open.

**Comment by marekjm** [comment]
Thanks @wting !
