### ISSUE TITLE
autojump import file from my own directory causing exception

### ISSUE THREAD

**Issue by tracyliang18** [wting/autojump#403]
I cd to a directory which happens to have the search.py file, which seems cause the following problem.
`~/tools/blocks/blocks on  master ⌚ 20:52:08
$ Traceback (most recent call last):
  File "/home/liangjj/.autojump/bin/autojump", line 43, in <module>
    from autojump_data import dictify
  File "/home/liangjj/.autojump/bin/autojump_data.py", line 20, in <module>
    from autojump_utils import create_dir
  File "/home/liangjj/.autojump/bin/autojump_utils.py", line 9, in <module>
    import platform
  File "/home/liangjj/tools/anaconda3/lib/python3.5/platform.py", line 117, in <module>
    import sys, os, re, subprocess
  File "/home/liangjj/tools/anaconda3/lib/python3.5/subprocess.py", line 438, in <module>
    import select
  File "/home/liangjj/tools/blocks/blocks/select.py", line 5, in <module>
    from picklable_itertools.extras import equizip
ImportError: No module named 'picklable_itertools'
`

**Comment by gwanii** [comment]
Just test that on my Mac, LGTM...

That's not autojump's problem,  here is the problem:
```
import select
File "/home/liangjj/tools/blocks/blocks/select.py", line 5, in 
```
