### ISSUE TITLE
Gracefully handle out of space error.

### ISSUE THREAD

**Issue by wting** [wting/autojump#451]
Right now it just barfs a Python stack trace and _loses all pre-existing data_.

```shell
╭─wting@nuc /home/backup ‹python-2.7.12›
╰─➤  Traceback (most recent call last):                                                                             2016.10.14 11:10:25 PDT 
  File "/home/wting/.autojump/bin/autojump", line 320, in <module>
    sys.exit(main(parse_arguments()))
  File "/home/wting/.autojump/bin/autojump", line 264, in main
    save(config, first(add_path(load(config), args.add)))
  File "/home/wting/.autojump/bin/autojump_data.py", line 138, in save
    move_file(temp.name, config['data_path'])
  File "/home/wting/.autojump/bin/autojump_utils.py", line 139, in move_file
    shutil.move(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
IOError: [Errno 28] No space left on device
ls
eikyo/  nuc/  tardis/
╭─wting@nuc /home/backup ‹python-2.7.12›
╰─➤                                                                                                                 2016.10.14 11:10:25 PDT 
```

**Comment by rmNULL** [comment]
this can be handled by moving the shutil call inside the try block. It would be nice if you can be a little more explicit on what "gracefully handle" means.
