### ISSUE TITLE
autojump doesnot work on ubuntu 16.04.2

### ISSUE THREAD

**Issue by oska874** [wting/autojump#477]
Today I updated ubuntu with `apt-get upgrade` ,but autojump doesnot works well. It shows error message below:

```
Traceback (most recent call last):
  File "/home/ezio/.autojump/bin/autojump", line 320, in <module>
    sys.exit(main(parse_arguments()))
  File "/home/ezio/.autojump/bin/autojump", line 292, in main
    entries = entriefy(load(config))
  File "/home/ezio/.autojump/bin/autojump_data.py", line 82, in load
    ifilter(correct_length, imap(parse, f))))
  File "/home/ezio/.autojump/bin/autojump_data.py", line 72, in <lambda>
    tupleize = lambda x: (x[1], float(x[0]))
UnicodeEncodeError: 'decimal' codec can't encode characters in position 2-3: invalid decimal Unicode string
autojump: directory 'xxx' not found
```

My environment is : 

```
uname -a
Linux *** 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
python --version
Python 2.7.12
```

```
autojump --version
autojump v22.5.1
```

Oh-my-zsh

```
zsh --version
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
```

**Comment by r-barnes** [comment]
Perhaps with the release of 18.04 this can be closed?
