### ISSUE TITLE
Unable to jump to folders with parentheses

### ISSUE THREAD

**Issue by pabloab** [wting/autojump#491]
Steps (from home):
1. `mkdir "a(b"`
1. `cd "a(b"/`
1. `j /home/myusr/a(b`

Got: ``bash: syntax error near unexpected token `('``
Expected: Just move to the folder as always

Maybe related to #267

**Comment by bendem** [comment]
just liked you needed quotes to create the directories, you need quotes when invoking `j`. `j "/home/myusr/a(b"` will work.

**Comment by pabloab** [comment]
I do the same steps with a directory with a space in it name and work perfectly. The problem is with parentheses. autojump suggest me the alternatives and just paste the whole path with the parentheses there, if I have to go to the start and to the end to put quotes then is not so handy/fast as it supposed. Either way, I tried with quotes **and autojump crash**:
```
pablo ~/a(b $ cd ..
pablo ~ $ j a__
a__1__/home/pablo/Downloads     
a__2__/home/pablo/a(b
pablo ~ $ j /home/pablo/a(b 
bash: syntax error near unexpected token `('
pablo ~ $ j "/home/pablo/a(b" 
Traceback (most recent call last):
  File "/usr/bin/autojump", line 420, in <module>
    sys.exit(main(parse_arguments()))
  File "/usr/bin/autojump", line 414, in main
    ['.'])))
  File "/usr/share/autojump/autojump_utils.py", line 42, in first
    return it.__next__()
  File "/usr/bin/autojump", line 287, in <lambda>
    flags=regex_flags)
  File "/usr/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python3.5/sre_parse.py", line 781, in _parse
    source.tell() - start)
sre_constants.error: missing ), unterminated subpattern at position 13
autojump: directory '/home/pablo/a(b' not found
\n\n
Try `autojump --help` for more information.
```
As you can see on the first line the directory exist.

**Comment by bendem** [comment]
What I'm saying is, `j /home/pablo/a(b` is a syntax error, the command never gets to autojump, it's just not a valid bash command.On Jul 24, 2017 01:31, Pablo <notifications@github.com> wrote:I do the same steps with a directory with a space in it name and work perfectly. The problem is with parentheses. autojump suggest me the alternatives and just paste the whole path with the parentheses there, if I have to go to the start and to the end to put quotes then is not so handy/fast as it supposed. Either way, I tried with quotes and autojump crash:
pablo ~/a(b $ cd ..
pablo ~ $ j a__
a__1__/home/pablo/Downloads     
a__2__/home/pablo/a(b
pablo ~ $ j /home/pablo/a(b 
bash: syntax error near unexpected token `('
pablo ~ $ j "/home/pablo/a(b" 
Traceback (most recent call last):
  File "/usr/bin/autojump", line 420, in <module>
    sys.exit(main(parse_arguments()))
  File "/usr/bin/autojump", line 414, in main
    ['.'])))
  File "/usr/share/autojump/autojump_utils.py", line 42, in first
    return it.__next__()
  File "/usr/bin/autojump", line 287, in <lambda>
    flags=regex_flags)
  File "/usr/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python3.5/sre_parse.py", line 781, in _parse
    source.tell() - start)
sre_constants.error: missing ), unterminated subpattern at position 13
autojump: directory '/home/pablo/a(b' not found
\n\n
Try `autojump --help` for more information.

As you can see on the first line the directory exist.

**Comment by bendem** [comment]
the error on `j "/home/pablo/a(b"` implies the user input should be escaped before trying to apply it as a regex search tho. That ought to be fixed

**Comment by pabloab** [comment]
Strange enough, I was able to jump to a folder with a space in it without closing with quotes. Recently I tried again and **autojump crash**:
```
Traceback (most recent call last):
  File "/usr/bin/autojump", line 420, in <module>
    sys.exit(main(parse_arguments()))
  File "/usr/bin/autojump", line 409, in main
    find_matches(entries, [tab_needle])))
  File "/usr/bin/autojump", line 405, in <lambda>
    get_ith_path = lambda i, iterable: last(take(i, iterable)).path
AttributeError: 'NoneType' object has no attribute 'path'
autojump: directory 'Aban__1' not found
\n\n
Try `autojump --help` for more information.
```
If quotes are needed also before autojump is reached maybe bash_completion script should be fixed.
This looks pretty critical, I hope @wting (or anyone with the time and knowledge) could see it soon.
BTW, I'm using autojump v22.2.4.
