### ISSUE TITLE
Not working in Windows 10

### ISSUE THREAD

**Issue by jsrraman** [wting/autojump#506]
I installed autojump as per the instructions for Windows. I navigate to a particular folder via "cd" for ex: "D:/projects" and then switch back to different folder and try `j projects`, it throws the following error

```
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\autojump\bin\\autojump", line 342, in <module>
    sys.exit(main(parse_arguments()))
  File "C:\Users\Dell\AppData\Local\autojump\bin\\autojump", line 335, in main
    ['.'],
  File "C:\Users\Dell\AppData\Local\autojump\bin\autojump_utils.py", line 41, in first
    return it.__next__()
  File "C:\Users\Dell\AppData\Local\autojump\bin\autojump_match.py", line 86, in <lambda>
    flags=regex_flags,
  File "D:\Program Files\Python\lib\re.py", line 182, in search
    return _compile(pattern, flags).search(string)
  File "D:\Program Files\Python\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "D:\Program Files\Python\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "D:\Program Files\Python\lib\sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "D:\Program Files\Python\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "D:\Program Files\Python\lib\sre_parse.py", line 523, in _parse
    source.tell() - here)
sre_constants.error: unterminated character set at position 5
ECHO is off.
```
However if I tried listing the paths added to the autojump database, i.e `j -s`, it correctly lists the just navigated paths.

*My environment*

OS: Windows 10
Python version: 3.6.3
autojump version: v22.5.1

**Comment by jerkovicl** [comment]
i got the same issue and same setup aswell

**Comment by thynctank** [comment]
I'm happy to dig in more at some point, but just started a new gig where I'm on a Win10 box. Was hoping to have autojump on my side, but as of now running `autojump -s` gets me:

```
0:       total weight
0:       number of entries
0.00:    current directory weight

data:    ~\AppData\Roaming\autojump\autojump.txt
```
... no matter how many times I cd through directories. Is it possible cd is not being overridden? If that's the case where should it happen?

I'll also say that neither that autjump directory no the autjump.txt file existed until I manually created them, and it's still not getting populated.

I've got GitBash running on this machine, but I've also tried with clink-ified cmd to no avail.

Several years ago I had autojump running fine in cygwin on Win7, but I don't remember having to really jump through many hoops.

Like I said, happy to devote time to a fix, but I'm pretty busy with work and my commute right now is 3hrs+ each way right now, so I likely won't have time till a weekend.

**Comment by SheepDomination** [comment]
@jsrraman How did you install for Windows10 ? I installed *clink* how do I actually install autojump ?

**Comment by wendingp** [comment]
@jsrraman @SheepDomination did you solve this?

**Comment by SheepDomination** [comment]
@wendingp no.
